[theme]
base = "dark"
primaryColor = "#f43f5e"
backgroundColor = "#09090b"
secondaryBackgroundColor = "#18181b"
textColor = "#fafafa"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
